// All countries
// length 252
export const countriesItems = [
    {id: 0,name: " ",alpha_3: " ",code: " ",currency: " ",symbol: " ",continent: " ",phone: 0,continent_code: " ",capital: " "},
    {id: 1,name: "Afghanistan",alpha_3: "AFG",code: "AF",currency: "AFN",symbol: "؋",continent: "Asia",phone: 93,continent_code: "AS",capital: "Kabul"},
    {id: 2,name: "Aland Islands",alpha_3: "ALA",code: "AX",currency: "EUR",symbol: "€",continent: "Europe",phone: 358,continent_code: "EU",capital: "Mariehamn"},
    {id: 3,name: "Albania",alpha_3: "ALB",code: "AL",currency: "ALL",symbol: "Lek",continent: "Europe",phone: 355,continent_code: "EU",capital: "Tirana"},
    {id: 4,name: "Algeria",alpha_3: "DZA",code: "DZ",currency: "DZD",symbol: "دج",continent: "Africa",phone: 213,continent_code: "AF",capital: "Algiers"},
    {id: 5,name: "American Samoa",alpha_3: "ASM",code: "AS",currency: "USD",symbol: "$",continent: "Oceania",phone: 1684,continent_code: "OC",capital: "Pago Pago"},
    {id: 6,name: "Andorra",alpha_3: "AND",code: "AD",currency: "EUR",symbol: "€",continent: "Europe",phone: 376,continent_code: "EU",capital: "Andorra la Vella"},
    {id: 7,name: "Angola",alpha_3: "AGO",code: "AO",currency: "AOA",symbol: "Kz",continent: "Africa",phone: 244,continent_code: "AF",capital: "Luanda"},
    {id: 8,name: "Anguilla",alpha_3: "AIA",code: "AI",currency: "XCD",symbol: "$",continent: "North America",phone: 1264,continent_code: "NA",capital: "The Valley"},
    {id: 9,name: "Antarctica",alpha_3: "ATA",code: "AQ",currency: "AAD",symbol: "$",continent: "Antarctica",phone: 672,continent_code: "AN",capital: "Antarctica"},
    {id: 10,name: "Antigua and Barbuda",alpha_3: "ATG",code: "AG",currency: "XCD",symbol: "$",continent: "North America",phone: 1268,continent_code: "NA",capital: "St. John's"},
    {id: 11,name: "Argentina",alpha_3: "ARG",code: "AR",currency: "ARS",symbol: "$",continent: "South America",phone: 54,continent_code: "SA",capital: "Buenos Aires"},
    {id: 12,name: "Armenia",alpha_3: "ARM",code: "AM",currency: "AMD",symbol: "֏",continent: "Asia",phone: 374,continent_code: "AS",capital: "Yerevan"},
    {id: 13,name: "Aruba",alpha_3: "ABW",code: "AW",currency: "AWG",symbol: "ƒ",continent: "North America",phone: 297,continent_code: "NA",capital: "Oranjestad"},
    {id: 14,name: "Australia",alpha_3: "AUS",code: "AU",currency: "AUD",symbol: "$",continent: "Oceania",phone: 61,continent_code: "OC",capital: "Canberra"},
    {id: 15,name: "Austria",alpha_3: "AUT",code: "AT",currency: "EUR",symbol: "€",continent: "Europe",phone: 43,continent_code: "EU",capital: "Vienna"},
    {id: 16,name: "Azerbaijan",alpha_3: "AZE",code: "AZ",currency: "AZN",symbol: "m",continent: "Asia",phone: 994,continent_code: "AS",capital: "Baku"},
    {id: 17,name: "Bahamas",alpha_3: "BHS",code: "BS",currency: "BSD",symbol: "B$",continent: "North America",phone: 1242,continent_code: "NA",capital: "Nassau"},
    {id: 18,name: "Bahrain",alpha_3: "BHR",code: "BH",currency: "BHD",symbol: ".د.ب",continent: "Asia",phone: 973,continent_code: "AS",capital: "Manama"},
    {id: 19,name: "Bangladesh",alpha_3: "BGD",code: "BD",currency: "BDT",symbol: "৳",continent: "Asia",phone: 880,continent_code: "AS",capital: "Dhaka"},
    {id: 20,name: "Barbados",alpha_3: "BRB",code: "BB",currency: "BBD",symbol: "Bds$",continent: "North America",phone: 1246,continent_code: "NA",capital: "Bridgetown"},
    {id: 21,name: "Belarus",alpha_3: "BLR",code: "BY",currency: "BYN",symbol: "Br",continent: "Europe",phone: 375,continent_code: "EU",capital: "Minsk"},
    {id: 22,name: "Belgium",alpha_3: "BEL",code: "BE",currency: "EUR",symbol: "€",continent: "Europe",phone: 32,continent_code: "EU",capital: "Brussels"},
    {id: 23,name: "Belize",alpha_3: "BLZ",code: "BZ",currency: "BZD",symbol: "$",continent: "North America",phone: 501,continent_code: "NA",capital: "Belmopan"},
    {id: 24,name: "Benin",alpha_3: "BEN",code: "BJ",currency: "XOF",symbol: "CFA",continent: "Africa",phone: 229,continent_code: "AF",capital: "Porto-Novo"},
    {id: 25,name: "Bermuda",alpha_3: "BMU",code: "BM",currency: "BMD",symbol: "$",continent: "North America",phone: 1441,continent_code: "NA",capital: "Hamilton"},
    {id: 26,name: "Bhutan",alpha_3: "BTN",code: "BT",currency: "BTN",symbol: "Nu.",continent: "Asia",phone: 975,continent_code: "AS",capital: "Thimphu"},
    {id: 27,name: "Bolivia",alpha_3: "BOL",code: "BO",currency: "BOB",symbol: "Bs.",continent: "South America",phone: 591,continent_code: "SA",capital: "Sucre"},
    {id: 28,name: "Bonaire, Sint Eustatius and Saba",alpha_3: "BES",code: "BQ",currency: "USD",symbol: "$",continent: "North America",phone: 599,continent_code: "NA",capital: "Kralendijk"},
    {id: 29,name: "Bosnia and Herzegovina",alpha_3: "BIH",code: "BA",currency: "BAM",symbol: "KM",continent: "Europe",phone: 387,continent_code: "EU",capital: "Sarajevo"},
    {id: 30,name: "Botswana",alpha_3: "BWA",code: "BW",currency: "BWP",symbol: "P",continent: "Africa",phone: 267,continent_code: "AF",capital: "Gaborone"},
    {id: 31,name: "Bouvet Island",alpha_3: "BVT",code: "BV",currency: "NOK",symbol: "kr",continent: "Antarctica",phone: 55,continent_code: "AN",capital: ""},
    {id: 32,name: "Brazil",alpha_3: "BRA",code: "BR",currency: "BRL",symbol: "R$",continent: "South America",phone: 55,continent_code: "SA",capital: "Brasilia"},
    {id: 33,name: "British Indian Ocean Territory",alpha_3: "IOT",code: "IO",currency: "USD",symbol: "$",continent: "Asia",phone: 246,continent_code: "AS",capital: "Diego Garcia"},
    {id: 34,name: "Brunei Darussalam",alpha_3: "BRN",code: "BN",currency: "BND",symbol: "B$",continent: "Asia",phone: 673,continent_code: "AS",capital: "Bandar Seri Begawan"},
    {id: 35,name: "Bulgaria",alpha_3: "BGR",code: "BG",currency: "BGN",symbol: "Лв.",continent: "Europe",phone: 359,continent_code: "EU",capital: "Sofia"},
    {id: 36,name: "Burkina Faso",alpha_3: "BFA",code: "BF",currency: "XOF",symbol: "CFA",continent: "Africa",phone: 226,continent_code: "AF",capital: "Ouagadougou"},
    {id: 37,name: "Burundi",alpha_3: "BDI",code: "BI",currency: "BIF",symbol: "FBu",continent: "Africa",phone: 257,continent_code: "AF",capital: "Bujumbura"},
    {id: 38,name: "Cambodia",alpha_3: "KHM",code: "KH",currency: "KHR",symbol: "KHR",continent: "Asia",phone: 855,continent_code: "AS",capital: "Phnom Penh"},
    {id: 39,name: "Cameroon",alpha_3: "CMR",code: "CM",currency: "XAF",symbol: "FCFA",continent: "Africa",phone: 237,continent_code: "AF",capital: "Yaounde"},
    {id: 40,name: "Canada",alpha_3: "CAN",code: "CA",currency: "CAD",symbol: "$",continent: "North America",phone: 1,continent_code: "NA",capital: "Ottawa"},
    {id: 41,name: "Cape Verde",alpha_3: "CPV",code: "CV",currency: "CVE",symbol: "$",continent: "Africa",phone: 238,continent_code: "AF",capital: "Praia"},
    {id: 42,name: "Cayman Islands",alpha_3: "CYM",code: "KY",currency: "KYD",symbol: "$",continent: "North America",phone: 1345,continent_code: "NA",capital: "George Town"},
    {id: 43,name: "Central African Republic",alpha_3: "CAF",code: "CF",currency: "XAF",symbol: "FCFA",continent: "Africa",phone: 236,continent_code: "AF",capital: "Bangui"},
    {id: 44,name: "Chad",alpha_3: "TCD",code: "TD",currency: "XAF",symbol: "FCFA",continent: "Africa",phone: 235,continent_code: "AF",capital: "N'Djamena"},
    {id: 45,name: "Chile",alpha_3: "CHL",code: "CL",currency: "CLP",symbol: "$",continent: "South America",phone: 56,continent_code: "SA",capital: "Santiago"},
    {id: 46,name: "China",alpha_3: "CHN",code: "CN",currency: "CNY",symbol: "¥",continent: "Asia",phone: 86,continent_code: "AS",capital: "Beijing"},
    {id: 47,name: "Christmas Island",alpha_3: "CXR",code: "CX",currency: "AUD",symbol: "$",continent: "Asia",phone: 61,continent_code: "AS",capital: "Flying Fish Cove"},
    {id: 48,name: "Cocos (Keeling) Islands",alpha_3: "CCK",code: "CC",currency: "AUD",symbol: "$",continent: "Asia",phone: 672,continent_code: "AS",capital: "West Island"},
    {id: 49,name: "Colombia",alpha_3: "COL",code: "CO",currency: "COP",symbol: "$",continent: "South America",phone: 57,continent_code: "SA",capital: "Bogota"},
    {id: 50,name: "Comoros",alpha_3: "COM",code: "KM",currency: "KMF",symbol: "CF",continent: "Africa",phone: 269,continent_code: "AF",capital: "Moroni"},
    {id: 51,name: "Congo",alpha_3: "COG",code: "CG",currency: "XAF",symbol: "FC",continent: "Africa",phone: 242,continent_code: "AF",capital: "Brazzaville"},
    {id: 52,name: "Congo, Democratic Republic of the Congo",alpha_3: "COD",code: "CD",currency: "CDF",symbol: "FC",continent: "Africa",phone: 242,continent_code: "AF",capital: "Kinshasa"},
    {id: 53,name: "Cook Islands",alpha_3: "COK",code: "CK",currency: "NZD",symbol: "$",continent: "Oceania",phone: 682,continent_code: "OC",capital: "Avarua"},
    {id: 54,name: "Costa Rica",alpha_3: "CRI",code: "CR",currency: "CRC",symbol: "₡",continent: "North America",phone: 506,continent_code: "NA",capital: "San Jose"},
    {id: 55,name: "Cote D'Ivoire",alpha_3: "CIV",code: "CI",currency: "XOF",symbol: "CFA",continent: "Africa",phone: 225,continent_code: "AF",capital: "Yamoussoukro"},
    {id: 56,name: "Croatia",alpha_3: "HRV",code: "HR",currency: "HRK",symbol: "kn",continent: "Europe",phone: 385,continent_code: "EU",capital: "Zagreb"},
    {id: 57,name: "Cuba",alpha_3: "CUB",code: "CU",currency: "CUP",symbol: "$",continent: "North America",phone: 53,continent_code: "NA",capital: "Havana"},
    {id: 58,name: "Curacao",alpha_3: "CUW",code: "CW",currency: "ANG",symbol: "ƒ",continent: "North America",phone: 599,continent_code: "NA",capital: "Willemstad"},
    {id: 59,name: "Cyprus",alpha_3: "CYP",code: "CY",currency: "EUR",symbol: "€",continent: "Asia",phone: 357,continent_code: "AS",capital: "Nicosia"},
    {id: 60,name: "Czech Republic",alpha_3: "CZE",code: "CZ",currency: "CZK",symbol: "Kč",continent: "Europe",phone: 420,continent_code: "EU",capital: "Prague"},
    {id: 61,name: "Denmark",alpha_3: "DNK",code: "DK",currency: "DKK",symbol: "Kr.",continent: "Europe",phone: 45,continent_code: "EU",capital: "Copenhagen"},
    {id: 62,name: "Djibouti",alpha_3: "DJI",code: "DJ",currency: "DJF",symbol: "Fdj",continent: "Africa",phone: 253,continent_code: "AF",capital: "Djibouti"},
    {id: 63,name: "Dominica",alpha_3: "DMA",code: "DM",currency: "XCD",symbol: "$",continent: "North America",phone: 1767,continent_code: "NA",capital: "Roseau"},
    {id: 64,name: "Dominican Republic",alpha_3: "DOM",code: "DO",currency: "DOP",symbol: "$",continent: "North America",phone: 1809,continent_code: "NA",capital: "Santo Domingo"},
    {id: 65,name: "Ecuador",alpha_3: "ECU",code: "EC",currency: "USD",symbol: "$",continent: "South America",phone: 593,continent_code: "SA",capital: "Quito"},
    {id: 66,name: "Egypt",alpha_3: "EGY",code: "EG",currency: "EGP",symbol: "ج.م",continent: "Africa",phone: 20,continent_code: "AF",capital: "Cairo"},
    {id: 67,name: "El Salvador",alpha_3: "SLV",code: "SV",currency: "USD",symbol: "$",continent: "North America",phone: 503,continent_code: "NA",capital: "San Salvador"},
    {id: 68,name: "Equatorial Guinea",alpha_3: "GNQ",code: "GQ",currency: "XAF",symbol: "FCFA",continent: "Africa",phone: 240,continent_code: "AF",capital: "Malabo"},
    {id: 69,name: "Eritrea",alpha_3: "ERI",code: "ER",currency: "ERN",symbol: "Nfk",continent: "Africa",phone: 291,continent_code: "AF",capital: "Asmara"},
    {id: 70,name: "Estonia",alpha_3: "EST",code: "EE",currency: "EUR",symbol: "€",continent: "Europe",phone: 372,continent_code: "EU",capital: "Tallinn"},
    {id: 71,name: "Ethiopia",alpha_3: "ETH",code: "ET",currency: "ETB",symbol: "Nkf",continent: "Africa",phone: 251,continent_code: "AF",capital: "Addis Ababa"},
    {id: 72,name: "Falkland Islands (Malvinas)",alpha_3: "FLK",code: "FK",currency: "FKP",symbol: "£",continent: "South America",phone: 500,continent_code: "SA",capital: "Stanley"},
    {id: 73,name: "Faroe Islands",alpha_3: "FRO",code: "FO",currency: "DKK",symbol: "Kr.",continent: "Europe",phone: 298,continent_code: "EU",capital: "Torshavn"},
    {id: 74,name: "Fiji",alpha_3: "FJI",code: "FJ",currency: "FJD",symbol: "FJ$",continent: "Oceania",phone: 679,continent_code: "OC",capital: "Suva"},
    {id: 75,name: "Finland",alpha_3: "FIN",code: "FI",currency: "EUR",symbol: "€",continent: "Europe",phone: 358,continent_code: "EU",capital: "Helsinki"},
    {id: 76,name: "France",alpha_3: "FRA",code: "FR",currency: "EUR",symbol: "€",continent: "Europe",phone: 33,continent_code: "EU",capital: "Paris"},
    {id: 77,name: "French Guiana",alpha_3: "GUF",code: "GF",currency: "EUR",symbol: "€",continent: "South America",phone: 594,continent_code: "SA",capital: "Cayenne"},
    {id: 78,name: "French Polynesia",alpha_3: "PYF",code: "PF",currency: "XPF",symbol: "₣",continent: "Oceania",phone: 689,continent_code: "OC",capital: "Papeete"},
    {id: 79,name: "French Southern Territories",alpha_3: "ATF",code: "TF",currency: "EUR",symbol: "€",continent: "Antarctica",phone: 262,continent_code: "AN",capital: "Port-aux-Francais"},
    {id: 80,name: "Gabon",alpha_3: "GAB",code: "GA",currency: "XAF",symbol: "FCFA",continent: "Africa",phone: 241,continent_code: "AF",capital: "Libreville"},
    {id: 81,name: "Gambia",alpha_3: "GMB",code: "GM",currency: "GMD",symbol: "D",continent: "Africa",phone: 220,continent_code: "AF",capital: "Banjul"},
    {id: 82,name: "Georgia",alpha_3: "GEO",code: "GE",currency: "GEL",symbol: "ლ",continent: "Asia",phone: 995,continent_code: "AS",capital: "Tbilisi"},
    {id: 83,name: "Germany",alpha_3: "DEU",code: "DE",currency: "EUR",symbol: "€",continent: "Europe",phone: 49,continent_code: "EU",capital: "Berlin"},
    {id: 84,name: "Ghana",alpha_3: "GHA",code: "GH",currency: "GHS",symbol: "GH₵",continent: "Africa",phone: 233,continent_code: "AF",capital: "Accra"},
    {id: 85,name: "Gibraltar",alpha_3: "GIB",code: "GI",currency: "GIP",symbol: "£",continent: "Europe",phone: 350,continent_code: "EU",capital: "Gibraltar"},
    {id: 86,name: "Greece",alpha_3: "GRC",code: "GR",currency: "EUR",symbol: "€",continent: "Europe",phone: 30,continent_code: "EU",capital: "Athens"},
    {id: 87,name: "Greenland",alpha_3: "GRL",code: "GL",currency: "DKK",symbol: "Kr.",continent: "North America",phone: 299,continent_code: "NA",capital: "Nuuk"},
    {id: 88,name: "Grenada",alpha_3: "GRD",code: "GD",currency: "XCD",symbol: "$",continent: "North America",phone: 1473,continent_code: "NA",capital: "St. George's"},
    {id: 89,name: "Guadeloupe",alpha_3: "GLP",code: "GP",currency: "EUR",symbol: "€",continent: "North America",phone: 590,continent_code: "NA",capital: "Basse-Terre"},
    {id: 90,name: "Guam",alpha_3: "GUM",code: "GU",currency: "USD",symbol: "$",continent: "Oceania",phone: 1671,continent_code: "OC",capital: "Hagatna"},
    {id: 91,name: "Guatemala",alpha_3: "GTM",code: "GT",currency: "GTQ",symbol: "Q",continent: "North America",phone: 502,continent_code: "NA",capital: "Guatemala City"},
    {id: 92,name: "Guernsey",alpha_3: "GGY",code: "GG",currency: "GBP",symbol: "£",continent: "Europe",phone: 44,continent_code: "EU",capital: "St Peter Port"},
    {id: 93,name: "Guinea",alpha_3: "GIN",code: "GN",currency: "GNF",symbol: "FG",continent: "Africa",phone: 224,continent_code: "AF",capital: "Conakry"},
    {id: 94,name: "Guinea-Bissau",alpha_3: "GNB",code: "GW",currency: "XOF",symbol: "CFA",continent: "Africa",phone: 245,continent_code: "AF",capital: "Bissau"},
    {id: 95,name: "Guyana",alpha_3: "GUY",code: "GY",currency: "GYD",symbol: "$",continent: "South America",phone: 592,continent_code: "SA",capital: "Georgetown"},
    {id: 96,name: "Haiti",alpha_3: "HTI",code: "HT",currency: "HTG",symbol: "G",continent: "North America",phone: 509,continent_code: "NA",capital: "Port-au-Prince"},
    {id: 97,name: "Heard Island and McDonald Islands",alpha_3: "HMD",code: "HM",currency: "AUD",symbol: "$",continent: "Antarctica",phone: 0,continent_code: "AN",capital: ""},
    {id: 98,name: "Holy See (Vatican City State)",alpha_3: "VAT",code: "VA",currency: "EUR",symbol: "€",continent: "Europe",phone: 39,continent_code: "EU",capital: "Vatican City"},
    {id: 99,name: "Honduras",alpha_3: "HND",code: "HN",currency: "HNL",symbol: "L",continent: "North America",phone: 504,continent_code: "NA",capital: "Tegucigalpa"},
    {id: 100,name: "Hong Kong",alpha_3: "HKG",code: "HK",currency: "HKD",symbol: "$",continent: "Asia",phone: 852,continent_code: "AS",capital: "Hong Kong"},
    {id: 101,name: "Hungary",alpha_3: "HUN",code: "HU",currency: "HUF",symbol: "Ft",continent: "Europe",phone: 36,continent_code: "EU",capital: "Budapest"},
    {id: 102,name: "Iceland",alpha_3: "ISL",code: "IS",currency: "ISK",symbol: "kr",continent: "Europe",phone: 354,continent_code: "EU",capital: "Reykjavik"},
    {id: 103,name: "India",alpha_3: "IND",code: "IN",currency: "INR",symbol: "₹",continent: "Asia",phone: 91,continent_code: "AS",capital: "New Delhi"},
    {id: 104,name: "Indonesia",alpha_3: "IDN",code: "ID",currency: "IDR",symbol: "Rp",continent: "Asia",phone: 62,continent_code: "AS",capital: "Jakarta"},
    {id: 105,name: "Iran, Islamic Republic of",alpha_3: "IRN",code: "IR",currency: "IRR",symbol: "﷼",continent: "Asia",phone: 98,continent_code: "AS",capital: "Tehran"},
    {id: 106,name: "Iraq",alpha_3: "IRQ",code: "IQ",currency: "IQD",symbol: "د.ع",continent: "Asia",phone: 964,continent_code: "AS",capital: "Baghdad"},
    {id: 107,name: "Ireland",alpha_3: "IRL",code: "IE",currency: "EUR",symbol: "€",continent: "Europe",phone: 353,continent_code: "EU",capital: "Dublin"},
    {id: 108,name: "Isle of Man",alpha_3: "IMN",code: "IM",currency: "GBP",symbol: "£",continent: "Europe",phone: 44,continent_code: "EU",capital: "Douglas, Isle of Man"},
    {id: 109,name: "Israel",alpha_3: "ISR",code: "IL",currency: "ILS",symbol: "₪",continent: "Asia",phone: 972,continent_code: "AS",capital: "Jerusalem"},
    {id: 110,name: "Italy",alpha_3: "ITA",code: "IT",currency: "EUR",symbol: "€",continent: "Europe",phone: 39,continent_code: "EU",capital: "Rome"},
    {id: 111,name: "Jamaica",alpha_3: "JAM",code: "JM",currency: "JMD",symbol: "J$",continent: "North America",phone: 1876,continent_code: "NA",capital: "Kingston"},
    {id: 112,name: "Japan",alpha_3: "JPN",code: "JP",currency: "JPY",symbol: "¥",continent: "Asia",phone: 81,continent_code: "AS",capital: "Tokyo"},
    {id: 113,name: "Jersey",alpha_3: "JEY",code: "JE",currency: "GBP",symbol: "£",continent: "Europe",phone: 44,continent_code: "EU",capital: "Saint Helier"},
    {id: 114,name: "Jordan",alpha_3: "JOR",code: "JO",currency: "JOD",symbol: "ا.د",continent: "Asia",phone: 962,continent_code: "AS",capital: "Amman"},
    {id: 115,name: "Kazakhstan",alpha_3: "KAZ",code: "KZ",currency: "KZT",symbol: "лв",continent: "Asia",phone: 7,continent_code: "AS",capital: "Astana"},
    {id: 116,name: "Kenya",alpha_3: "KEN",code: "KE",currency: "KES",symbol: "KSh",continent: "Africa",phone: 254,continent_code: "AF",capital: "Nairobi"},
    {id: 117,name: "Kiribati",alpha_3: "KIR",code: "KI",currency: "AUD",symbol: "$",continent: "Oceania",phone: 686,continent_code: "OC",capital: "Tarawa"},
    {id: 118,name: "Korea, Democratic People's Republic of",alpha_3: "PRK",code: "KP",currency: "KPW",symbol: "₩",continent: "Asia",phone: 850,continent_code: "AS",capital: "Pyongyang"},
    {id: 119,name: "Korea, Republic of",alpha_3: "KOR",code: "KR",currency: "KRW",symbol: "₩",continent: "Asia",phone: 82,continent_code: "AS",capital: "Seoul"},
    {id: 120,name: "Kosovo",alpha_3: "XKX",code: "XK",currency: "EUR",symbol: "€",continent: "Europe",phone: 383,continent_code: "EU",capital: "Pristina"},
    {id: 121,name: "Kuwait",alpha_3: "KWT",code: "KW",currency: "KWD",symbol: "ك.د",continent: "Asia",phone: 965,continent_code: "AS",capital: "Kuwait City"},
    {id: 122,name: "Kyrgyzstan",alpha_3: "KGZ",code: "KG",currency: "KGS",symbol: "лв",continent: "Asia",phone: 996,continent_code: "AS",capital: "Bishkek"},
    {id: 123,name: "Lao People's Democratic Republic",alpha_3: "LAO",code: "LA",currency: "LAK",symbol: "₭",continent: "Asia",phone: 856,continent_code: "AS",capital: "Vientiane"},
    {id: 124,name: "Latvia",alpha_3: "LVA",code: "LV",currency: "EUR",symbol: "€",continent: "Europe",phone: 371,continent_code: "EU",capital: "Riga"},
    {id: 125,name: "Lebanon",alpha_3: "LBN",code: "LB",currency: "LBP",symbol: "£",continent: "Asia",phone: 961,continent_code: "AS",capital: "Beirut"},
    {id: 126,name: "Lesotho",alpha_3: "LSO",code: "LS",currency: "LSL",symbol: "L",continent: "Africa",phone: 266,continent_code: "AF",capital: "Maseru"},
    {id: 127,name: "Liberia",alpha_3: "LBR",code: "LR",currency: "LRD",symbol: "$",continent: "Africa",phone: 231,continent_code: "AF",capital: "Monrovia"},
    {id: 128,name: "Libyan Arab Jamahiriya",alpha_3: "LBY",code: "LY",currency: "LYD",symbol: "د.ل",continent: "Africa",phone: 218,continent_code: "AF",capital: "Tripolis"},
    {id: 129,name: "Liechtenstein",alpha_3: "LIE",code: "LI",currency: "CHF",symbol: "CHf",continent: "Europe",phone: 423,continent_code: "EU",capital: "Vaduz"},
    {id: 130,name: "Lithuania",alpha_3: "LTU",code: "LT",currency: "EUR",symbol: "€",continent: "Europe",phone: 370,continent_code: "EU",capital: "Vilnius"},
    {id: 131,name: "Luxembourg",alpha_3: "LUX",code: "LU",currency: "EUR",symbol: "€",continent: "Europe",phone: 352,continent_code: "EU",capital: "Luxembourg"},
    {id: 132,name: "Macao",alpha_3: "MAC",code: "MO",currency: "MOP",symbol: "$",continent: "Asia",phone: 853,continent_code: "AS",capital: "Macao"},
    {id: 133,name: "Macedonia, the Former Yugoslav Republic of",alpha_3: "MKD",code: "MK",currency: "MKD",symbol: "ден",continent: "Europe",phone: 389,continent_code: "EU",capital: "Skopje"},
    {id: 134,name: "Madagascar",alpha_3: "MDG",code: "MG",currency: "MGA",symbol: "Ar",continent: "Africa",phone: 261,continent_code: "AF",capital: "Antananarivo"},
    {id: 135,name: "Malawi",alpha_3: "MWI",code: "MW",currency: "MWK",symbol: "MK",continent: "Africa",phone: 265,continent_code: "AF",capital: "Lilongwe"},
    {id: 136,name: "Malaysia",alpha_3: "MYS",code: "MY",currency: "MYR",symbol: "RM",continent: "Asia",phone: 60,continent_code: "AS",capital: "Kuala Lumpur"},
    {id: 137,name: "Maldives",alpha_3: "MDV",code: "MV",currency: "MVR",symbol: "Rf",continent: "Asia",phone: 960,continent_code: "AS",capital: "Male"},
    {id: 138,name: "Mali",alpha_3: "MLI",code: "ML",currency: "XOF",symbol: "CFA",continent: "Africa",phone: 223,continent_code: "AF",capital: "Bamako"},
    {id: 139,name: "Malta",alpha_3: "MLT",code: "MT",currency: "EUR",symbol: "€",continent: "Europe",phone: 356,continent_code: "EU",capital: "Valletta"},
    {id: 140,name: "Marshall Islands",alpha_3: "MHL",code: "MH",currency: "USD",symbol: "$",continent: "Oceania",phone: 692,continent_code: "OC",capital: "Majuro"},
    {id: 141,name: "Martinique",alpha_3: "MTQ",code: "MQ",currency: "EUR",symbol: "€",continent: "North America",phone: 596,continent_code: "NA",capital: "Fort-de-France"},
    {id: 142,name: "Mauritania",alpha_3: "MRT",code: "MR",currency: "MRO",symbol: "MRU",continent: "Africa",phone: 222,continent_code: "AF",capital: "Nouakchott"},
    {id: 143,name: "Mauritius",alpha_3: "MUS",code: "MU",currency: "MUR",symbol: "₨",continent: "Africa",phone: 230,continent_code: "AF",capital: "Port Louis"},
    {id: 144,name: "Mayotte",alpha_3: "MYT",code: "YT",currency: "EUR",symbol: "€",continent: "Africa",phone: 262,continent_code: "AF",capital: "Mamoudzou"},
    {id: 145,name: "Mexico",alpha_3: "MEX",code: "MX",currency: "MXN",symbol: "$",continent: "North America",phone: 52,continent_code: "NA",capital: "Mexico City"},
    {id: 146,name: "Micronesia, Federated States of",alpha_3: "FSM",code: "FM",currency: "USD",symbol: "$",continent: "Oceania",phone: 691,continent_code: "OC",capital: "Palikir"},
    {id: 147,name: "Moldova, Republic of",alpha_3: "MDA",code: "MD",currency: "MDL",symbol: "L",continent: "Europe",phone: 373,continent_code: "EU",capital: "Chisinau"},
    {id: 148,name: "Monaco",alpha_3: "MCO",code: "MC",currency: "EUR",symbol: "€",continent: "Europe",phone: 377,continent_code: "EU",capital: "Monaco"},
    {id: 149,name: "Mongolia",alpha_3: "MNG",code: "MN",currency: "MNT",symbol: "₮",continent: "Asia",phone: 976,continent_code: "AS",capital: "Ulan Bator"},
    {id: 150,name: "Montenegro",alpha_3: "MNE",code: "ME",currency: "EUR",symbol: "€",continent: "Europe",phone: 382,continent_code: "EU",capital: "Podgorica"},
    {id: 151,name: "Montserrat",alpha_3: "MSR",code: "MS",currency: "XCD",symbol: "$",continent: "North America",phone: 1664,continent_code: "NA",capital: "Plymouth"},
    {id: 152,name: "Morocco",alpha_3: "MAR",code: "MA",currency: "MAD",symbol: "DH",continent: "Africa",phone: 212,continent_code: "AF",capital: "Rabat"},
    {id: 153,name: "Mozambique",alpha_3: "MOZ",code: "MZ",currency: "MZN",symbol: "MT",continent: "Africa",phone: 258,continent_code: "AF",capital: "Maputo"},
    {id: 154,name: "Myanmar",alpha_3: "MMR",code: "MM",currency: "MMK",symbol: "K",continent: "Asia",phone: 95,continent_code: "AS",capital: "Nay Pyi Taw"},
    {id: 155,name: "Namibia",alpha_3: "NAM",code: "NA",currency: "NAD",symbol: "$",continent: "Africa",phone: 264,continent_code: "AF",capital: "Windhoek"},
    {id: 156,name: "Nauru",alpha_3: "NRU",code: "NR",currency: "AUD",symbol: "$",continent: "Oceania",phone: 674,continent_code: "OC",capital: "Yaren"},
    {id: 157,name: "Nepal",alpha_3: "NPL",code: "NP",currency: "NPR",symbol: "₨",continent: "Asia",phone: 977,continent_code: "AS",capital: "Kathmandu"},
    {id: 158,name: "Netherlands",alpha_3: "NLD",code: "NL",currency: "EUR",symbol: "€",continent: "Europe",phone: 31,continent_code: "EU",capital: "Amsterdam"},
    {id: 159,name: "Netherlands Antilles",alpha_3: "ANT",code: "AN",currency: "ANG",symbol: "NAf",continent: "North America",phone: 599,continent_code: "NA",capital: "Willemstad"},
    {id: 160,name: "New Caledonia",alpha_3: "NCL",code: "NC",currency: "XPF",symbol: "₣",continent: "Oceania",phone: 687,continent_code: "OC",capital: "Noumea"},
    {id: 161,name: "New Zealand",alpha_3: "NZL",code: "NZ",currency: "NZD",symbol: "$",continent: "Oceania",phone: 64,continent_code: "OC",capital: "Wellington"},
    {id: 162,name: "Nicaragua",alpha_3: "NIC",code: "NI",currency: "NIO",symbol: "C$",continent: "North America",phone: 505,continent_code: "NA",capital: "Managua"},
    {id: 163,name: "Niger",alpha_3: "NER",code: "NE",currency: "XOF",symbol: "CFA",continent: "Africa",phone: 227,continent_code: "AF",capital: "Niamey"},
    {id: 164,name: "Nigeria",alpha_3: "NGA",code: "NG",currency: "NGN",symbol: "₦",continent: "Africa",phone: 234,continent_code: "AF",capital: "Abuja"},
    {id: 165,name: "Niue",alpha_3: "NIU",code: "NU",currency: "NZD",symbol: "$",continent: "Oceania",phone: 683,continent_code: "OC",capital: "Alofi"},
    {id: 166,name: "Norfolk Island",alpha_3: "NFK",code: "NF",currency: "AUD",symbol: "$",continent: "Oceania",phone: 672,continent_code: "OC",capital: "Kingston"},
    {id: 167,name: "Northern Mariana Islands",alpha_3: "MNP",code: "MP",currency: "USD",symbol: "$",continent: "Oceania",phone: 1670,continent_code: "OC",capital: "Saipan"},
    {id: 168,name: "Norway",alpha_3: "NOR",code: "NO",currency: "NOK",symbol: "kr",continent: "Europe",phone: 47,continent_code: "EU",capital: "Oslo"},
    {id: 169,name: "Oman",alpha_3: "OMN",code: "OM",currency: "OMR",symbol: ".ع.ر",continent: "Asia",phone: 968,continent_code: "AS",capital: "Muscat"},
    {id: 170,name: "Pakistan",alpha_3: "PAK",code: "PK",currency: "PKR",symbol: "₨",continent: "Asia",phone: 92,continent_code: "AS",capital: "Islamabad"},
    {id: 171,name: "Palau",alpha_3: "PLW",code: "PW",currency: "USD",symbol: "$",continent: "Oceania",phone: 680,continent_code: "OC",capital: "Melekeok"},
    {id: 172,name: "Palestinian Territory, Occupied",alpha_3: "PSE",code: "PS",currency: "ILS",symbol: "₪",continent: "Asia",phone: 970,continent_code: "AS",capital: "East Jerusalem"},
    {id: 173,name: "Panama",alpha_3: "PAN",code: "PA",currency: "PAB",symbol: "B/.",continent: "North America",phone: 507,continent_code: "NA",capital: "Panama City"},
    {id: 174,name: "Papua New Guinea",alpha_3: "PNG",code: "PG",currency: "PGK",symbol: "K",continent: "Oceania",phone: 675,continent_code: "OC",capital: "Port Moresby"},
    {id: 175,name: "Paraguay",alpha_3: "PRY",code: "PY",currency: "PYG",symbol: "₲",continent: "South America",phone: 595,continent_code: "SA",capital: "Asuncion"},
    {id: 176,name: "Peru",alpha_3: "PER",code: "PE",currency: "PEN",symbol: "S/.",continent: "South America",phone: 51,continent_code: "SA",capital: "Lima"},
    {id: 177,name: "Philippines",alpha_3: "PHL",code: "PH",currency: "PHP",symbol: "₱",continent: "Asia",phone: 63,continent_code: "AS",capital: "Manila"},
    {id: 178,name: "Pitcairn",alpha_3: "PCN",code: "PN",currency: "NZD",symbol: "$",continent: "Oceania",phone: 64,continent_code: "OC",capital: "Adamstown"},
    {id: 179,name: "Poland",alpha_3: "POL",code: "PL",currency: "PLN",symbol: "zł",continent: "Europe",phone: 48,continent_code: "EU",capital: "Warsaw"},
    {id: 180,name: "Portugal",alpha_3: "PRT",code: "PT",currency: "EUR",symbol: "€",continent: "Europe",phone: 351,continent_code: "EU",capital: "Lisbon"},
    {id: 181,name: "Puerto Rico",alpha_3: "PRI",code: "PR",currency: "USD",symbol: "$",continent: "North America",phone: 1787,continent_code: "NA",capital: "San Juan"},
    {id: 182,name: "Qatar",alpha_3: "QAT",code: "QA",currency: "QAR",symbol: "ق.ر",continent: "Asia",phone: 974,continent_code: "AS",capital: "Doha"},
    {id: 183,name: "Reunion",alpha_3: "REU",code: "RE",currency: "EUR",symbol: "€",continent: "Africa",phone: 262,continent_code: "AF",capital: "Saint-Denis"},
    {id: 184,name: "Romania",alpha_3: "ROM",code: "RO",currency: "RON",symbol: "lei",continent: "Europe",phone: 40,continent_code: "EU",capital: "Bucharest"},
    {id: 185,name: "Russian Federation",alpha_3: "RUS",code: "RU",currency: "RUB",symbol: "₽",continent: "Asia",phone: 7,continent_code: "AS",capital: "Moscow"},
    {id: 186,name: "Rwanda",alpha_3: "RWA",code: "RW",currency: "RWF",symbol: "FRw",continent: "Africa",phone: 250,continent_code: "AF",capital: "Kigali"},
    {id: 187,name: "Saint Barthelemy",alpha_3: "BLM",code: "BL",currency: "EUR",symbol: "€",continent: "North America",phone: 590,continent_code: "NA",capital: "Gustavia"},
    {id: 188,name: "Saint Helena",alpha_3: "SHN",code: "SH",currency: "SHP",symbol: "£",continent: "Africa",phone: 290,continent_code: "AF",capital: "Jamestown"},
    {id: 189,name: "Saint Kitts and Nevis",alpha_3: "KNA",code: "KN",currency: "XCD",symbol: "$",continent: "North America",phone: 1869,continent_code: "NA",capital: "Basseterre"},
    {id: 190,name: "Saint Lucia",alpha_3: "LCA",code: "LC",currency: "XCD",symbol: "$",continent: "North America",phone: 1758,continent_code: "NA",capital: "Castries"},
    {id: 191,name: "Saint Martin",alpha_3: "MAF",code: "MF",currency: "EUR",symbol: "€",continent: "North America",phone: 590,continent_code: "NA",capital: "Marigot"},
    {id: 192,name: "Saint Pierre and Miquelon",alpha_3: "SPM",code: "PM",currency: "EUR",symbol: "€",continent: "North America",phone: 508,continent_code: "NA",capital: "Saint-Pierre"},
    {id: 193,name: "Saint Vincent and the Grenadines",alpha_3: "VCT",code: "VC",currency: "XCD",symbol: "$",continent: "North America",phone: 1784,continent_code: "NA",capital: "Kingstown"},
    {id: 194,name: "Samoa",alpha_3: "WSM",code: "WS",currency: "WST",symbol: "SAT",continent: "Oceania",phone: 684,continent_code: "OC",capital: "Apia"},
    {id: 195,name: "San Marino",alpha_3: "SMR",code: "SM",currency: "EUR",symbol: "€",continent: "Europe",phone: 378,continent_code: "EU",capital: "San Marino"},
    {id: 196,name: "Sao Tome and Principe",alpha_3: "STP",code: "ST",currency: "STD",symbol: "Db",continent: "Africa",phone: 239,continent_code: "AF",capital: "Sao Tome"},
    {id: 197,name: "Saudi Arabia",alpha_3: "SAU",code: "SA",currency: "SAR",symbol: "﷼",continent: "Asia",phone: 966,continent_code: "AS",capital: "Riyadh"},
    {id: 198,name: "Senegal",alpha_3: "SEN",code: "SN",currency: "XOF",symbol: "CFA",continent: "Africa",phone: 221,continent_code: "AF",capital: "Dakar"},
    {id: 199,name: "Serbia",alpha_3: "SRB",code: "RS",currency: "RSD",symbol: "din",continent: "Europe",phone: 381,continent_code: "EU",capital: "Belgrade"},
    {id: 200,name: "Serbia and Montenegro",alpha_3: "SCG",code: "CS",currency: "RSD",symbol: "din",continent: "Europe",phone: 381,continent_code: "EU",capital: "Belgrade"},
    {id: 201,name: "Seychelles",alpha_3: "SYC",code: "SC",currency: "SCR",symbol: "SRe",continent: "Africa",phone: 248,continent_code: "AF",capital: "Victoria"},
    {id: 202,name: "Sierra Leone",alpha_3: "SLE",code: "SL",currency: "SLL",symbol: "Le",continent: "Africa",phone: 232,continent_code: "AF",capital: "Freetown"},
    {id: 203,name: "Singapore",alpha_3: "SGP",code: "SG",currency: "SGD",symbol: "$",continent: "Asia",phone: 65,continent_code: "AS",capital: "Singapur"},
    {id: 204,name: "St Martin",alpha_3: "SXM",code: "SX",currency: "ANG",symbol: "ƒ",continent: "North America",phone: 721,continent_code: "NA",capital: "Philipsburg"},
    {id: 205,name: "Slovakia",alpha_3: "SVK",code: "SK",currency: "EUR",symbol: "€",continent: "Europe",phone: 421,continent_code: "EU",capital: "Bratislava"},
    {id: 206,name: "Slovenia",alpha_3: "SVN",code: "SI",currency: "EUR",symbol: "€",continent: "Europe",phone: 386,continent_code: "EU",capital: "Ljubljana"},
    {id: 207,name: "Solomon Islands",alpha_3: "SLB",code: "SB",currency: "SBD",symbol: "Si$",continent: "Oceania",phone: 677,continent_code: "OC",capital: "Honiara"},
    {id: 208,name: "Somalia",alpha_3: "SOM",code: "SO",currency: "SOS",symbol: "Sh.so.",continent: "Africa",phone: 252,continent_code: "AF",capital: "Mogadishu"},
    {id: 209,name: "South Africa",alpha_3: "ZAF",code: "ZA",currency: "ZAR",symbol: "R",continent: "Africa",phone: 27,continent_code: "AF",capital: "Pretoria"},
    {id: 210,name: "South Georgia and the South Sandwich Islands",alpha_3: "SGS",code: "GS",currency: "GBP",symbol: "£",continent: "Antarctica",phone: 500,continent_code: "AN",capital: "Grytviken"},
    {id: 211,name: "South Sudan",alpha_3: "SSD",code: "SS",currency: "SSP",symbol: "£",continent: "Africa",phone: 211,continent_code: "AF",capital: "Juba"},
    {id: 212,name: "Spain",alpha_3: "ESP",code: "ES",currency: "EUR",symbol: "€",continent: "Europe",phone: 34,continent_code: "EU",capital: "Madrid"},
    {id: 213,name: "Sri Lanka",alpha_3: "LKA",code: "LK",currency: "LKR",symbol: "Rs",continent: "Asia",phone: 94,continent_code: "AS",capital: "Colombo"},
    {id: 214,name: "Sudan",alpha_3: "SDN",code: "SD",currency: "SDG",symbol: ".س.ج",continent: "Africa",phone: 249,continent_code: "AF",capital: "Khartoum"},
    {id: 215,name: "Suriname",alpha_3: "SUR",code: "SR",currency: "SRD",symbol: "$",continent: "South America",phone: 597,continent_code: "SA",capital: "Paramaribo"},
    {id: 216,name: "Svalbard and Jan Mayen",alpha_3: "SJM",code: "SJ",currency: "NOK",symbol: "kr",continent: "Europe",phone: 47,continent_code: "EU",capital: "Longyearbyen"},
    {id: 217,name: "Swaziland",alpha_3: "SWZ",code: "SZ",currency: "SZL",symbol: "E",continent: "Africa",phone: 268,continent_code: "AF",capital: "Mbabane"},
    {id: 218,name: "Sweden",alpha_3: "SWE",code: "SE",currency: "SEK",symbol: "kr",continent: "Europe",phone: 46,continent_code: "EU",capital: "Stockholm"},
    {id: 219,name: "Switzerland",alpha_3: "CHE",code: "CH",currency: "CHF",symbol: "CHf",continent: "Europe",phone: 41,continent_code: "EU",capital: "Berne"},
    {id: 220,name: "Syrian Arab Republic",alpha_3: "SYR",code: "SY",currency: "SYP",symbol: "LS",continent: "Asia",phone: 963,continent_code: "AS",capital: "Damascus"},
    {id: 221,name: "Taiwan, Province of China",alpha_3: "TWN",code: "TW",currency: "TWD",symbol: "$",continent: "Asia",phone: 886,continent_code: "AS",capital: "Taipei"},
    {id: 222,name: "Tajikistan",alpha_3: "TJK",code: "TJ",currency: "TJS",symbol: "SM",continent: "Asia",phone: 992,continent_code: "AS",capital: "Dushanbe"},
    {id: 223,name: "Tanzania, United Republic of",alpha_3: "TZA",code: "TZ",currency: "TZS",symbol: "TSh",continent: "Africa",phone: 255,continent_code: "AF",capital: "Dodoma"},
    {id: 224,name: "Thailand",alpha_3: "THA",code: "TH",currency: "THB",symbol: "฿",continent: "Asia",phone: 66,continent_code: "AS",capital: "Bangkok"},
    {id: 225,name: "Timor-Leste",alpha_3: "TLS",code: "TL",currency: "USD",symbol: "$",continent: "Asia",phone: 670,continent_code: "AS",capital: "Dili"},
    {id: 226,name: "Togo",alpha_3: "TGO",code: "TG",currency: "XOF",symbol: "CFA",continent: "Africa",phone: 228,continent_code: "AF",capital: "Lome"},
    {id: 227,name: "Tokelau",alpha_3: "TKL",code: "TK",currency: "NZD",symbol: "$",continent: "Oceania",phone: 690,continent_code: "OC",capital: ""},
    {id: 228,name: "Tonga",alpha_3: "TON",code: "TO",currency: "TOP",symbol: "$",continent: "Oceania",phone: 676,continent_code: "OC",capital: "Nuku'alofa"},
    {id: 229,name: "Trinidad and Tobago",alpha_3: "TTO",code: "TT",currency: "TTD",symbol: "$",continent: "North America",phone: 1868,continent_code: "NA",capital: "Port of Spain"},
    {id: 230,name: "Tunisia",alpha_3: "TUN",code: "TN",currency: "TND",symbol: "ت.د",continent: "Africa",phone: 216,continent_code: "AF",capital: "Tunis"},
    {id: 231,name: "Turkey",alpha_3: "TUR",code: "TR",currency: "TRY",symbol: "₺",continent: "Asia",phone: 90,continent_code: "AS",capital: "Ankara"},
    {id: 232,name: "Turkmenistan",alpha_3: "TKM",code: "TM",currency: "TMT",symbol: "T",continent: "Asia",phone: 7370,continent_code: "AS",capital: "Ashgabat"},
    {id: 233,name: "Turks and Caicos Islands",alpha_3: "TCA",code: "TC",currency: "USD",symbol: "$",continent: "North America",phone: 1649,continent_code: "NA",capital: "Cockburn Town"},
    {id: 234,name: "Tuvalu",alpha_3: "TUV",code: "TV",currency: "AUD",symbol: "$",continent: "Oceania",phone: 688,continent_code: "OC",capital: "Funafuti"},
    {id: 235,name: "Uganda",alpha_3: "UGA",code: "UG",currency: "UGX",symbol: "USh",continent: "Africa",phone: 256,continent_code: "AF",capital: "Kampala"},
    {id: 236,name: "Ukraine",alpha_3: "UKR",code: "UA",currency: "UAH",symbol: "₴",continent: "Europe",phone: 380,continent_code: "EU",capital: "Kiev"},
    {id: 237,name: "United Arab Emirates",alpha_3: "ARE",code: "AE",currency: "AED",symbol: "إ.د",continent: "Asia",phone: 971,continent_code: "AS",capital: "Abu Dhabi"},
    {id: 238,name: "United Kingdom",alpha_3: "GBR",code: "GB",currency: "GBP",symbol: "£",continent: "Europe",phone: 44,continent_code: "EU",capital: "London"},
    {id: 239,name: "United States",alpha_3: "USA",code: "US",currency: "USD",symbol: "$",continent: "North America",phone: 1,continent_code: "NA",capital: "Washington"},
    {id: 240,name: "United States Minor Outlying Islands",alpha_3: "UMI",code: "UM",currency: "USD",symbol: "$",continent: "North America",phone: 1,continent_code: "NA",capital: ""},
    {id: 241,name: "Uruguay",alpha_3: "URY",code: "UY",currency: "UYU",symbol: "$",continent: "South America",phone: 598,continent_code: "SA",capital: "Montevideo"},
    {id: 242,name: "Uzbekistan",alpha_3: "UZB",code: "UZ",currency: "UZS",symbol: "лв",continent: "Asia",phone: 998,continent_code: "AS",capital: "Tashkent"},
    {id: 243,name: "Vanuatu",alpha_3: "VUT",code: "VU",currency: "VUV",symbol: "VT",continent: "Oceania",phone: 678,continent_code: "OC",capital: "Port Vila"},
    {id: 244,name: "Venezuela",alpha_3: "VEN",code: "VE",currency: "VEF",symbol: "Bs",continent: "South America",phone: 58,continent_code: "SA",capital: "Caracas"},
    {id: 245,name: "Viet Nam",alpha_3: "VNM",code: "VN",currency: "VND",symbol: "₫",continent: "Asia",phone: 84,continent_code: "AS",capital: "Hanoi"},
    {id: 246,name: "Virgin Islands, British",alpha_3: "VGB",code: "VG",currency: "USD",symbol: "$",continent: "North America",phone: 1284,continent_code: "NA",capital: "Road Town"},
    {id: 247,name: "Virgin Islands, U.s.",alpha_3: "VIR",code: "VI",currency: "USD",symbol: "$",continent: "North America",phone: 1340,continent_code: "NA",capital: "Charlotte Amalie"},
    {id: 248,name: "Wallis and Futuna",alpha_3: "WLF",code: "WF",currency: "XPF",symbol: "₣",continent: "Oceania",phone: 681,continent_code: "OC",capital: "Mata Utu"},
    {id: 249,name: "Western Sahara",alpha_3: "ESH",code: "EH",currency: "MAD",symbol: "MAD",continent: "Africa",phone: 212,continent_code: "AF",capital: "El-Aaiun"},
    {id: 250,name: "Yemen",alpha_3: "YEM",code: "YE",currency: "YER",symbol: "﷼",continent: "Asia",phone: 967,continent_code: "AS",capital: "Sanaa"},
    {id: 251,name: "Zambia",alpha_3: "ZMB",code: "ZM",currency: "ZMW",symbol: "ZK",continent: "Africa",phone: 260,continent_code: "AF",capital: "Lusaka"},
    {id: 252,name: "Zimbabwe",alpha_3: "ZWE",code: "ZW",currency: "ZWL",symbol: "$",continent: "Africa",phone: 263,continent_code: "AF",capital: "Harare"}
];